name: Deploy Infra

on:
  workflow_dispatch:

jobs:
  deploy-infra:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy frontend infra
      run: |
        aws cloudformation deploy \
          --template-file cloudformation/frontend.yaml \
          --stack-name required-remainder-frontend \
          --capabilities CAPABILITY_NAMED_IAM
